data_api/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('jeju/list', views.call_api_jeju, name='call_api_jeu'),
]

main/urls.py
from django.urls import path
from . import views


app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("predict/", views.predict, name="predict"),
    path("predict_image/", views.predict_image, name="predict_image"),
    path("image_result/", views.image_result, name="image_result"),
]

tutorial_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("main/", include("main.urls")),
    path("api/", include("data_api.urls")),
]

data_api/models.py
from django.db import models
from django.db.models import Model


# Create your models here.


class JejuValuePlace(models.Model):
    # 읍면동
    emdNM = models.CharField(max_length=100, null=True)
    # 업소 명
    bsshNm = models.CharField(max_length=200,null=True)
    # 업종 명
    indutyNm = models.CharField(max_length=200,null=True)
    # 도로명 주소
    rnAdres = models.CharField(max_length=200,null=True)
    # 업소 전화번호
    bsshTelno = models.CharField(max_length=200,null=True)
    # 품목 내용
    prdlstCn = models.CharField(max_length=200,null=True)
    # 기타 내용
    etcCn = models.CharField(max_length=200,null=True)
    # 등록 일시
    regDt = models.CharField(max_length=200,null=True)
    # 위도
    laCrdnt = models.CharField(max_length=200,null=True)
    # 경도
    loCrdnt = models.CharField(max_length=200,null=True)
    # 데이터 코드
    dataCd = models.CharField(max_length=200,null=True)
    # 선정 연도
    slctnYr = models.CharField(max_length=200,null=True)
    # 선정 월
    slctnMm = models.CharField(max_length=200,null=True)

    def __str__(self):
        return f"{self.emdNM} {self.bsshNm} {self.indutyNm} {self.rnAdres} {self.bsshTelno} {self.prdlstCn} {self.etcCn} {self.regDt} {self.laCrdnt} {self.loCrdnt} {self.dataCd} {self.slctnYr} {self.slctnMm}"

    meta = {
        'db_table': 'jeju_value_place'
    }

main/models.py
from django.db import models

# Create your models here.

data_api/views.py
import requests
from django.shortcuts import render
from .models import JejuValuePlace

from django.conf import settings

DATA_API_KEY = settings.DATA_API_KEY


# Create your views here.


def call_api_jeju(request):
    # 쿼리 파라미터 방식
    page_no = int(request.GET.get("pageNo", 1))

    # api 요청
    url_base = f"http://apis.data.go.kr/6510000/goodPriceStoreService/getGoodPirceStoreList?ServiceKey={DATA_API_KEY}"

    if page_no > 1:
        url_base += f"&pageNo={page_no}"

    res_data = requests.get(url_base)

    # 안티패턴
    if not res_data.status_code == 200 or page_no < 1:
        return render(request, "error_500.html")

    api_data = res_data.json()

    total_page = api_data['response']['body']['totalCount']
    page_no = api_data['response']['body']['pageNo']
    items = api_data['response']['body']['items']['item']
    end_page_number = (total_page // 10) + 1

    data = {
        "total_page": total_page,
        "page_no": page_no,
        "items": items,
        "end_page_number": end_page_number,
    }
    for v in items:
        save_jeju_value_place_data(v)

    return render(request, "api_list.html", {"data": data})


def save_jeju_value_place_data(val: dict):
    if not JejuValuePlace.objects.filter(bsshNm=val.get('bsshNm')).exists():
        JejuValuePlace.objects.create(
            emdNM=val.get('emdNm', None),
            bsshNm=val.get('bsshNm', None),
            indutyNm=val.get('indutyNm', None),
            rnAdres=val.get('rnAdres', None),
            bsshTelno=val.get('bsshTelno', None),
            prdlstCn=val.get('prdlstCn', None),
            etcCn=val.get('etcCn', None),
            regDt=val.get('regDt', None),
            laCrdnt=val.get('laCrdnt', None),
            loCrdnt=val.get('loCrdnt', None),
            dataCd=val.get('dataCd', None),
            slctnYr=val.get('slctnYr', None),
            slctnMm=val.get('slctnMm', None),
        )

main/views.py
from django.shortcuts import render, redirect
from transformers import pipeline
from diffusers import StableDiffusionPipeline
import torch
from transformers import TrOCRProcessor, VisionEncoderDecoderModel, AutoTokenizer
import requests
import unicodedata
from io import BytesIO
from PIL import Image


# Create your views here.


def index(request):
    get_prediction = request.session.get('prediction', None)
    if get_prediction is not None:
        prediction = get_prediction[0]['generated_text']
        request.session.delete('prediction')
    else:
        prediction = None
    return render(request, "main.html", {"prediction": prediction})


def predict(request):
    data = request.POST.get("sentence")

    model_name = "heegyu/ajoublue-gpt2-base"
    pipe = pipeline('text-generation', model=model_name)

    prediction = pipe(data, repetition_penalty=1.2, eos_token_id=1, early_stopping=False,
                      max_new_tokens=128, min_length=64)

    request.session['prediction'] = prediction

    return redirect("main:index")


def predict_image(request):
    data = request.FILES.get("image_file", None)

    if data:
        processor = TrOCRProcessor.from_pretrained("ddobokki/ko-trocr")
        model = VisionEncoderDecoderModel.from_pretrained("ddobokki/ko-trocr")
        tokenizer = AutoTokenizer.from_pretrained("ddobokki/ko-trocr")

        img = Image.open(BytesIO(data.read()))

        pixel_values = processor(img, return_tensors="pt").pixel_values
        generated_ids = model.generate(pixel_values, max_length=64)
        generated_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
        generated_text = unicodedata.normalize("NFC", generated_text)
        request.session['image'] = generated_text

    else:

        return render(request, "image_result.html")

    return redirect("main:image_result")


def image_result(request):
    image = request.session.get('image', None)

    if image is not None:
        image_data = image
        request.session.delete('image')
    else:
        image_data = None

    return render(request, "image_result.html", {"image": image_data})

data_api/templates/api_list.html
{% load static %}
{% load mathfilters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <style>
        table, th, thead{
            text-align: center;
            vertical-align : middle;
        }
    </style>
</head>
<body>
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                    <thead>
                    <tr>
                        <th><abbr title="업소 명">업소 명</abbr></th>
                        <th><abbr>읍면동</abbr></th>
                        <th><abbr>업종 명</abbr></th>
                        <th><abbr>도로명 주소</abbr></th>
                        <th><abbr>업소 전화번호</abbr></th>
                        <th><abbr>품목 내용</abbr></th>
                        <th><abbr>기타 내용</abbr></th>
                        <th><abbr>등록 일시</abbr></th>
                        <th class="has-text-centered"><abbr>위도</abbr></th>
                        <th class="has-text-centered"><abbr>경도</abbr></th>
                        <th><abbr>데이터 코드</abbr></th>
                        <th><abbr>선정 연도</abbr></th>
                        <th><abbr>선정 월</abbr></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in data.items %}
                        <tr>
                            <td><a href="https://map.naver.com/p/search/{{ item.rnAdres }}"
                                   target="_blank">{{ item.bsshNm }}</a>
                            </td>
                            <td>{{ item.emdNM }}</td>
                            <td>{{ item.indutyNm }}</td>
                            <td>{{ item.rnAdres }}</td>
                            <td>{{ item.bsshTelno }}</td>
                            <td>{{ item.prdlstCn }}</td>
                            <td>{{ item.etcCn }}</td>
                            <td>{{ item.regDt }}</td>
                            <td>{{ item.laCrdnt }}</td>
                            <td>{{ item.loCrdnt }}</td>
                            <td>{{ item.dataCd }}</td>
                            <td>{{ item.slctnYr }}</td>
                            <td>{{ item.slctnMm }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</section>
<nav class="pagination is-rounded is-centered" role="navigation" aria-label="pagination">
    {% if data.page_no > 1 %}
        <a class="pagination-previous" href="?pageNo={{ data.page_no | add:-1 }}">이전 페이지</a>
    {% else %}
        <a class="pagination-previous" disabled>이전 페이지</a>
    {% endif %}
    <a class="pagination-next" href="?pageNo={{ data.page_no | add:1 }}">다음 페이지</a>
    <ul class="pagination-list">
        {% if data.page_no > 1 %}
            <li><a class="pagination-link" aria-label="Goto_page_1" href="?pageNo=1">1</a></li>
        {% endif %}
        {% if data.page_no > 2 %}
            <li><a class="pagination-link" aria-label="Goto_page_2" href="?pageNo=2">2</a></li>
        {% endif %}
        {% if data.page_no > 3 %}
            <li><span class="pagination-ellipsis">&hellip;</span></li>
        {% endif %}
        <li><a class="pagination-link is-current" aria-label="Page_current" aria-current="page">{{ data.page_no }}</a></li>
        {% if data.end_page_number != data.page_no %}
            <li><a class="pagination-link" aria-label="Goto_next_page" href="?pageNo={{ data.page_no | add:1 }}">{{ data.page_no | add:1 }}</a></li>
            <li><span class="pagination-ellipsis">&hellip;</span></li>
        <li><a class="pagination-link" aria-label="Goto_page_last" href="?pageNo={{ data.end_page_number }}">{{ data.end_page_number }}</a></li>
        {% endif %}

    </ul>
</nav>

</body>
</html>

data_api/templates/error_500.html
{%  load static %}
<head>
    <meta charset="UTF-8">
    <title>500</title>
    <link rel="stylesheet" href="{% static 'css/500.scss' %}">
</head>
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
<div class="message">
  <h1>500</h1>
  <h3>Server Error</h3>
  <h2>API 응답이 성공적으로 처리되지 않았어요.</h2>
</div>

main/templates/image_result.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>OCR 이미지 분석 페이지</title>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
</head>
<body>
<div class="container">
    <div>
        <h1 class="title">OCR 이미지 분석 페이지</h1>
        <form action="{% url 'main:predict_image' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="field">
                <label class="label">이미지 추가</label>
                <div class="control">
                    <input type="file" class="form" name="image_file" id="imageFile">
                </div>
            </div>
            <br>
            <div class="field">
                <div class="control">
                    <button class="button is-link">이미지 분석</button>
                </div>
            </div>
        </form>
    </div>
    {% if image %}
        <br>
        <br>
        <div>
            <h2 class="subtitle">분석된 이미지 내용</h2>
            <div>
                <h1>
                    <strong>{{ image }}</strong>
                </h1>
            </div>
        </div>
    {% endif %}
</div>
</body>
</html>

main/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>허깅페이스 페이지</title>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
</head>
<body>
<div class="container">
    <form class="from" action="{% url 'main:predict' %}" method="post">
        {% csrf_token %}
        <div class="field">
            <label class="label">입력 문장</label>
            <div class="control">
                <input class="input" type="text" name="sentence" placeholder="입력 문장을 입력하세요.">
            </div>
        </div>
        <div class="field">
            <div class="control">
                <button class="button is-link" type="submit">예측</button>
            </div>
        </div>
    </form>
    {% if prediction %}
        <div class="field">
        <label class="label">결과</label>
        <div class="control">
            <input class="input" type="text" value="{{ prediction }}" readonly>
        </div>
    {% endif %}
    </div>
</body>
</html>